<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username-sername-0d5</name>
   <tag></tag>
   <elementGuidId>34b157cb-2772-48c4-a4c9-fb439d3fcb55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full > div.w-full.text-darkCharcoal.relative.input-box > #mb-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'username' and @id = 'mb-username' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b97a50-552d-4abe-b4a1-87961996a0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2.5 box-border disabled:opacity-50 disabled:bg-gray-100 remove-default-eye w-full h-full rounded-brRadius border font-primary text-base font-normal lowercase border-gray-600</value>
      <webElementGuid>47ae57e8-fcfc-4c66-8dbf-fc0d66f4b306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>5e63bcc9-4fd3-4209-9cad-e13cdb5538cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mb-username</value>
      <webElementGuid>a90c418d-e438-45b1-a4df-928d346c2091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email / Username</value>
      <webElementGuid>afc1acc5-4be5-44ae-a2a3-0d28152ff237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>424e478e-517c-45f6-9f20-30086806ec1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>230bec34-0709-4e99-9f9d-183255b63623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e96c0b53-e718-4bdc-a267-d9c555d5fbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>a63e42d7-1376-4777-9b25-981a6523701b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full text-darkCharcoal relative input-box&quot;]/input[@id=&quot;mb-username&quot;]</value>
      <webElementGuid>7ce4fe18-0557-40b8-a50f-835a23a7c310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tc1/Page_Student HomePage/mb-text-input_Social sign in_username</value>
      <webElementGuid>73aeca97-3730-45eb-960a-1c454f5b1c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecff200a-2774-4ff0-9b05-8ae4f2a56ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'mb-username' and @type = 'text']</value>
      <webElementGuid>8c19358f-23de-44fe-9cff-8afd17461a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
