<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password-assword-0e6</name>
   <tag></tag>
   <elementGuidId>1eb86f1a-b2bb-41fc-afc7-09ccf14b5e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full > div.w-full.text-darkCharcoal.relative.input-box > #mb-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'password' and @id = 'mb-password' and @type = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1db942bc-0baf-402f-9c88-bf8542a79333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2.5 box-border disabled:opacity-50 disabled:bg-gray-100 remove-default-eye w-full h-full rounded-brRadius border font-primary text-base font-normal border-gray-600</value>
      <webElementGuid>666d46c9-ad34-4d9c-913f-836131bd6efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d3d28123-b979-455a-97d0-c99028dbc262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mb-password</value>
      <webElementGuid>a397245f-ece2-4eee-b58b-df32354de6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>f7cd931b-05df-41e4-9e16-6a9952414d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56f51672-8836-4c48-937c-fb243f7c398b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b111e04e-c893-4cd5-abd0-1fac3e0b23ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>035f073e-f0e5-4497-a66b-afbb409cdfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>63870583-2d1b-466e-8383-6c1f7366563e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full text-darkCharcoal relative input-box&quot;]/input[@id=&quot;mb-password&quot;]</value>
      <webElementGuid>d98081cf-7a75-4e73-b16f-9210d995b378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tc1/Page_Student HomePage/mb-text-input_Social sign in_password</value>
      <webElementGuid>1ca3927e-540e-4aa1-ab71-16883cedf7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42c98e57-11e9-4a7d-87fe-c2b35996e44a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'mb-password' and @type = 'password']</value>
      <webElementGuid>afbd7291-7a98-4fb2-a258-70ae37820494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
