<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mb-button_Sign In</name>
   <tag></tag>
   <elementGuidId>af1a191f-5b90-4523-b7a6-b127a0271d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applyButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mb-button[@id='applyButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mb-button</value>
      <webElementGuid>13d28156-3ac2-4a8f-89cc-dedc2f317d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyButton</value>
      <webElementGuid>053ad6d1-c05a-4d56-b312-872be8749daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>cd5a5891-f3cd-4102-bdce-ce7e8953633b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>2a4be5ad-168c-42ca-8c45-ef93d2ae259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-button</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>678582a3-aeb2-4ff6-b6a8-4849da1fe9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-submit-btn hydrated</value>
      <webElementGuid>d244c6ea-0d05-4005-8ed2-05c5e4ad8cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyButton&quot;)</value>
      <webElementGuid>b7baf6c3-fb8d-4f8e-bd21-fe7c272323b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mb-button[@id='applyButton']</value>
      <webElementGuid>46e290aa-a874-42b5-9279-1c083543d981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_auth']/main/div/div/div/div/div[3]/form/div[3]/mb-button</value>
      <webElementGuid>b7bcabb5-b2f2-4345-b150-0baf987eb784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mb-button</value>
      <webElementGuid>e970b621-b5e8-4ea5-81ed-e04fcb02960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mb-button[@id = 'applyButton' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>fe212593-2e8f-48c1-ad35-093ef93ebb1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
