<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mb-text-input_Social sign in_username</name>
   <tag></tag>
   <elementGuidId>3d000c9f-74b0-4326-b0bd-3be44cf245c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mb-text-input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mb-text-input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mb-text-input</value>
      <webElementGuid>e696adc6-d179-4089-8729-96840024f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>99e01f9f-fbb7-4723-a9cc-9cc5ffdd6a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e431466-469c-4842-90a0-68172b8f7562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c0545b9-2f68-46f8-abdd-610028a2889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5d1800c-07cc-4ebc-84cb-2b6a77d26457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Email / Username</value>
      <webElementGuid>a3bcbe6e-65fb-4c32-bc84-f8a22b52bcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>input-id</name>
      <type>Main</type>
      <value>mb-username</value>
      <webElementGuid>ece35c38-40cb-4e78-acd6-fb4670dff9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>e09a4483-c32b-4259-b0a8-e4923e950734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_auth&quot;)/main[1]/div[@class=&quot;lg:auth-flex lg:auth-flex-row auth-bg-white&quot;]/div[@class=&quot;lg:auth-w-1/2 auth-h-[100dvh]&quot;]/div[@class=&quot;auth-mx-4 lg:auth-mx-auto lg:auth-w-auto auth-flex auth-flex-col auth-justify-between auth-h-full&quot;]/div[1]/div[@class=&quot;auth-px-[15px] md:auth-px-[121px]&quot;]/form[@class=&quot;md:auth-flex md:auth-flex-col md:auth-items-center lg:auth-items-start&quot;]/div[@class=&quot;auth-mb-[25px] md:auth-w-full md:auth-max-w-[466px]&quot;]/mb-text-input[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>ead0b4ed-b1f2-4ec5-98d8-786055ecfe51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mb-text-input[@name='username']</value>
      <webElementGuid>eabb17ba-f510-41df-99cc-6e1587ee4ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_auth']/main/div/div/div/div/div[3]/form/div/mb-text-input</value>
      <webElementGuid>153bf477-353a-406c-89f4-5d23eeade8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mb-text-input</value>
      <webElementGuid>966aa641-76ac-47cd-9139-6340a6fb6b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mb-text-input[@name = 'username' and @type = 'text']</value>
      <webElementGuid>d701e5af-8ae4-475a-b0d3-7aaf5dcb06b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
