<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mb-text-input_Social sign in_password</name>
   <tag></tag>
   <elementGuidId>8f5867fd-a857-4749-83f3-c04c7485954d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mb-text-input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mb-text-input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mb-text-input</value>
      <webElementGuid>68218299-937a-46d0-9395-686875a601e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a6ab2e12-cfba-43ec-b225-a7366408e523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>253e6b3b-857a-4497-8c5a-781f09d0017c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>51ca2d0e-2cc1-47a9-8724-4bde676e9962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17964749-777f-4e39-9248-9445c516c8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c08a265a-48eb-4385-ac4e-7037ff575d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>input-id</name>
      <type>Main</type>
      <value>mb-password</value>
      <webElementGuid>01cbc970-5e26-4f5f-999c-98b2d17eb657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>e968d303-43a4-49d1-ab1d-118cc55bfc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_auth&quot;)/main[1]/div[@class=&quot;lg:auth-flex lg:auth-flex-row auth-bg-white&quot;]/div[@class=&quot;lg:auth-w-1/2 auth-h-[100dvh]&quot;]/div[@class=&quot;auth-mx-4 lg:auth-mx-auto lg:auth-w-auto auth-flex auth-flex-col auth-justify-between auth-h-full&quot;]/div[1]/div[@class=&quot;auth-px-[15px] md:auth-px-[121px]&quot;]/form[@class=&quot;md:auth-flex md:auth-flex-col md:auth-items-center lg:auth-items-start&quot;]/div[@class=&quot;auth-mb-[75px] md:auth-w-full md:auth-max-w-[466px]&quot;]/mb-text-input[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>706176dd-8424-481f-9c52-6570094cea71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mb-text-input[@name='password']</value>
      <webElementGuid>ddc9c244-d102-4dc4-a261-a8615a536e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_auth']/main/div/div/div/div/div[3]/form/div[2]/mb-text-input</value>
      <webElementGuid>3a386b24-1087-42a1-b41c-43077b93beae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mb-text-input</value>
      <webElementGuid>66184417-9473-42fc-9937-95b3f8d2a056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mb-text-input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>eae8ef6a-60aa-45ed-8485-73f199b5ee31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
